#!/bin/bash

if [ -z "$VIRTUAL_ENV" ]; then
    source /usr/local/bin/virtualenvwrapper.sh
    workon current_project
fi

scripts/search_for_focused_specs.sh && scripts/python_linter.sh && scripts/all_local_tests.sh
RETCODE=$?

sleep 1
exit $RETCODE
