#!/bin/bash

if [ -z "$VIRTUAL_ENV" ]; then
    source /usr/local/bin/virtualenvwrapper.sh
    workon $(basename $(pwd))
fi

dev -t search_focused_specs && dev -t all_tests
RETCODE=$?

sleep 1
exit $RETCODE
