#!/bin/bash

if [ -z "$VIRTUAL_ENV" ]; then
    source /usr/local/bin/virtualenvwrapper.sh
    workon $(basename $(pwd))
fi

focused_specs && linter staged && fast_tests
RETCODE=$?

sleep 1
exit $RETCODE
